#!/bin/bash
# ===========================================
# Nginx Webhook Receiver
# ===========================================
# Di-deploy di VPS Nginx (yang punya IP public)
# Menerima request dari PaaS VPS untuk:
#   - Generate nginx config
#   - Generate SSL certificate (Let's Encrypt)
#   - Hapus config saat project dihapus
# ===========================================
# Dependencies: socat, certbot
# Install: apt install socat certbot
# ===========================================

# Configuration
WEBHOOK_PORT="${WEBHOOK_PORT:-5000}"
WEBHOOK_SECRET="${WEBHOOK_SECRET:-change-this-secret}"
BASE_DOMAIN="${BASE_DOMAIN:-horn-yastudio.com}"
NGINX_CONF_DIR="${NGINX_CONF_DIR:-/etc/nginx/conf.d}"
ACME_EMAIL="${ACME_EMAIL:-admin@horn-yastudio.com}"
WEBROOT="${WEBROOT:-/usr/share/nginx/html}"
BACKEND_HOST="${BACKEND_HOST:-192.168.255.116}"  # IP VPS Laravel PaaS
LOG_FILE="${LOG_FILE:-/var/log/nginx-webhook.log}"

# Ensure directories exist
mkdir -p "$NGINX_CONF_DIR"
mkdir -p "$(dirname "$LOG_FILE")"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Generate nginx config (HTTP only - for initial deploy)
generate_http_config() {
    local subdomain="$1"
    local port="$2"
    local full_domain="${subdomain}.${BASE_DOMAIN}"
    
    cat > "${NGINX_CONF_DIR}/${subdomain}.conf" << EOF
# Auto-generated by Laravel PaaS Webhook
# Project: ${subdomain}
# Backend: ${BACKEND_HOST}:80 (via Traefik)

server {
    listen 80;
    server_name ${full_domain};

    # Let's Encrypt verification
    location /.well-known {
        alias ${WEBROOT}/.well-known;
    }
    
    location / {
        return 301 https://\$host\$request_uri;
    }
}
EOF
    }

    location / {
        proxy_pass http://${backend_ip}:${port}/;
        include /etc/nginx/proxy_params;
    }
}
EOF
}

# Generate nginx config with SSL
generate_ssl_config() {
    local subdomain="$1"
    local port="$2"
    local full_domain="${subdomain}.${BASE_DOMAIN}"
    
    cat > "${NGINX_CONF_DIR}/${subdomain}.conf" << EOF
# Auto-generated by Laravel PaaS Webhook
# Project: ${subdomain}
# Backend: ${BACKEND_HOST}:80 (via Traefik)

server {
    listen 80;
    server_name ${full_domain};

    location /.well-known {
        alias ${WEBROOT}/.well-known;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name ${full_domain};

    ssl_certificate /etc/letsencrypt/live/${full_domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${full_domain}/privkey.pem;
    include /etc/nginx/ssl_params;

    access_log /var/log/nginx/${full_domain}.access.log;
    error_log  /var/log/nginx/${full_domain}.error.log;

    location / {
        proxy_pass http://${BACKEND_HOST}/;
        proxy_set_header Host ${full_domain};
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
    }
}
EOF

    access_log /var/log/nginx/${subdomain}.access.log;
    error_log /var/log/nginx/${subdomain}.error.log;

    location / {
        proxy_pass http://${backend_ip}:${port}/;
        include /etc/nginx/proxy_params;
    }
}
EOF
}

# conf.d doesn't need symlinks - files are auto-loaded

# Reload nginx
reload_nginx() {
    nginx -t && nginx -s reload
}

# Generate SSL certificate
generate_ssl() {
    local domain="$1"
    
    # Check if cert already exists
    if [ -f "/etc/letsencrypt/live/${domain}/fullchain.pem" ]; then
        log "SSL cert already exists for ${domain}"
        return 0
    fi
    
    certbot certonly \
        --webroot \
        -w "$WEBROOT" \
        -d "$domain" \
        --email "$ACME_EMAIL" \
        --agree-tos \
        --non-interactive \
        --quiet
}

# Handle CREATE request
handle_create() {
    local subdomain="$1"
    local backend_ip="$2"
    local port="$3"
    local full_domain="${subdomain}.${BASE_DOMAIN}"
    
    log "CREATE: ${subdomain} -> ${backend_ip}:${port}"
    
    # Step 1: Generate HTTP config
    generate_http_config "$subdomain" "$backend_ip" "$port"
    reload_nginx
    
    # Step 2: Generate SSL
    if generate_ssl "$full_domain"; then
        # Step 3: Update to SSL config
        generate_ssl_config "$subdomain" "$backend_ip" "$port"
        reload_nginx
        log "SUCCESS: ${full_domain} with SSL"
        echo '{"success":true,"ssl":true}'
    else
        log "WARNING: ${full_domain} without SSL (cert failed)"
        echo '{"success":true,"ssl":false}'
    fi
}

# Handle DELETE request
handle_delete() {
    local subdomain="$1"
    local full_domain="${subdomain}.${BASE_DOMAIN}"
    
    log "DELETE: ${subdomain}"
    
    # Remove nginx config
    rm -f "${NGINX_CONF_DIR}/${subdomain}.conf"
    reload_nginx
    
    # Remove SSL certificate
    if [ -d "/etc/letsencrypt/live/${full_domain}" ]; then
        log "Removing SSL cert for ${full_domain}"
        certbot delete --cert-name "${full_domain}" --non-interactive 2>/dev/null || \
        rm -rf "/etc/letsencrypt/live/${full_domain}" \
               "/etc/letsencrypt/archive/${full_domain}" \
               "/etc/letsencrypt/renewal/${full_domain}.conf"
    fi
    
    log "SUCCESS: ${subdomain} removed (config + SSL)"
    echo '{"success":true}'
}

# Parse HTTP request and handle
handle_request() {
    local request=""
    local content_length=0
    local body=""
    
    # Read HTTP headers
    while IFS= read -r line; do
        line="${line%%$'\r'}"
        [ -z "$line" ] && break
        
        if [[ "$line" == POST* ]]; then
            request="$line"
        elif [[ "$line" == Content-Length:* ]]; then
            content_length="${line#Content-Length: }"
        elif [[ "$line" == X-Webhook-Secret:* ]]; then
            auth="${line#X-Webhook-Secret: }"
        fi
    done
    
    # Read body
    if [ "$content_length" -gt 0 ]; then
        body=$(head -c "$content_length")
    fi
    
    # Check auth
    if [ "$auth" != "$WEBHOOK_SECRET" ]; then
        log "UNAUTHORIZED request"
        echo -e "HTTP/1.1 401 Unauthorized\r\nContent-Type: application/json\r\n\r\n{\"error\":\"unauthorized\"}"
        return
    fi
    
    # Parse JSON body (simple extraction)
    subdomain=$(echo "$body" | grep -oP '"subdomain"\s*:\s*"\K[^"]+')
    backend_ip=$(echo "$body" | grep -oP '"backend_ip"\s*:\s*"\K[^"]+')
    port=$(echo "$body" | grep -oP '"port"\s*:\s*\K[0-9]+')
    
    # Route request
    local response=""
    if [[ "$request" == *"/create"* ]] || [[ "$request" == *"/update"* ]]; then
        response=$(handle_create "$subdomain" "$backend_ip" "$port")
    elif [[ "$request" == *"/delete"* ]]; then
        response=$(handle_delete "$subdomain")
    elif [[ "$request" == *"/health"* ]]; then
        response='{"status":"ok"}'
    else
        response='{"error":"unknown endpoint"}'
    fi
    
    # Send response
    echo -e "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: ${#response}\r\n\r\n${response}"
}

# Main loop - listen for connections
log "Starting Nginx Webhook on port ${WEBHOOK_PORT}"
log "Base domain: ${BASE_DOMAIN}"
log "Nginx conf.d: ${NGINX_CONF_DIR}"

while true; do
    # Use socat to handle HTTP connections
    socat TCP-LISTEN:${WEBHOOK_PORT},reuseaddr,fork EXEC:"$0 --handle-request"
done
